from abc import ABC


class BaseRepository(ABC):

    def index(self, *args, **kwargs): ...

    def show(self, *args, **kwargs): ...
    
    def store(self, *args, **kwargs): ...
    
    def update(self, *args, **kwargs): ...
    
    def delete(self, *args, **kwargs): ...